project:
  type: website
  output-dir: docs

website:
  title: "Omnis tempus datum"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/pgg1610
      - icon: twitter
        href: https://twitter.com/mepgg
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    toc: true

